### ISSUE TITLE
Clear up confusion with the Proximity and Con_Proximity

### ISSUE THREAD

**Issue by rowedenny** [aamir-mustafa/pcl-adversarial-defense#12]
Sorry to bother, but referring to the code, I am more confused with the Proximity and Con_Proximity

1. The second term in eq5 has two terms: the average distance between x and non-label centers, and the average distance between all non-label center pairs. Yet in Con_Proximity, the distance between non-label pairs seem not to account. In other words, the codes does not show the term that maintaining a large distance between each prototype.

2. Based on my understanding, the centers are expected to be shared between Proximity and Con_Proximity, however, the attribute centers are individual independent for both class, it seems that the center in Proximity and Con_Proximity are not shared.

Would you mind pointing out any flaw on my interpretation, and share your thoughts about it?

**Comment by aamir-mustafa** [comment]
Hey, Thanks for the interest in our work.
1. Considering the traingulation, the code for Con_Proximity inherently takes care of that. 
2. Since the centres are updated at the end of each epoch, we made an assumption that the centers for Proximity and Con_Priximity would be close enough, if not the same.

Hope that helps
